module.exports = {
    simple: {
        name: 'simple',
        maxGoal: 1000,
        numbers: [ 4 ],
        infixOperators: [ '*', '/', '+', '-' ],
        prefixOperators: null,
        postfixOperators: null,
        maxFactorial: 0,
        maxExponent: 0,
        maxSquare: 0,
        maxSum: 0,
    },
    power: {
        name: 'power',
        maxGoal: 1000,
        numbers: [ 4 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: null,
        postfixOperators: null,
        maxFactorial: 0,
        maxExponent: 50,
        maxSquare: 0,
        maxSum: 0,
    },
    concat: {
        name: 'concat',
        maxGoal: 1000,
        numbers: [ 4, 44, 444, 4444 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: null,
        postfixOperators: null,
        maxFactorial: 0,
        maxExponent: 50,
        maxSquare: 0,
        maxSum: 0,
    },
    decimal: {
        name: 'decimal',
        maxGoal: 1000,
        numbers: [ 4, 44, 444, 4444, .4, 4.4, .44, 44.4, 4.44, .444, 444.4, 44.44, 4.444, .4444 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: null,
        postfixOperators: null,
        maxFactorial: 0,
        maxExponent: 50,
        maxSquare: 0,
        maxSum: 0,
    },
    factorial: {
        name: 'factorial',
        maxGoal: 1000,
        numbers: [ 4, 44, 444, 4444, .4, 4.4, .44, 44.4, 4.44, .444, 444.4, 44.44, 4.444, .4444 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: null,
        postfixOperators: [ '!' ],
        maxFactorial: 10,
        maxExponent: 50,
        maxSquare: 0,
        maxSum: 0,
    },
    functions: {
        name: 'functions',
        maxGoal: 1000,
        numbers: [ 4, 44, 444, 4444, .4, 4.4, .44, 44.4, 4.44, .444, 444.4, 44.44, 4.444, .4444 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: [ 'sqrt', 'square', 'sum' ],
        postfixOperators: null,
        maxFactorial: 10,
        maxExponent: 10,
        maxSquare: 100,
        maxSum: 100,
    },
    advanced: {
        name: 'advanced',
        maxGoal: 1000,
        numbers: [ 4, 44, 444, 4444, .4, 4.4, .44, 44.4, 4.44, .444, 444.4, 44.44, 4.444, .4444 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: [ 'sqrt', 'square', 'sum' ],
        postfixOperators: [ '!' ],
        maxFactorial: 10,
        maxExponent: 10,
        maxSquare: 100,
        maxSum: 100,
    },
};
