module.exports = {
    simple: {
        name: 'simple',
        maxGoal: 1000,
        numbers: [ 4 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: null,
        postfixOperators: null,
        maxFactorial: 0,
        maxExponent: 0,
        maxSquare: 0,
        maxSum: 0,
        applyToEvaluation: false,
    },
    factorial: {
        name: 'factorial',
        maxGoal: 1000,
        numbers: [ 4 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: null,
        postfixOperators: [ '!' ],
        maxFactorial: 10,
        maxExponent: 50,
        maxSquare: 0,
        maxSum: 0,
        applyToEvaluation: false,
    },
    functions: {
        name: 'functions',
        maxGoal: 1000,
        numbers: [ 4 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: [ 'sqrt', 'square', 'sum' ],
        postfixOperators: null,
        maxFactorial: 10,
        maxExponent: 10,
        maxSquare: 100,
        maxSum: 100,
        applyToEvaluation: false,
    },
    combined: {
        name: 'combined',
        maxGoal: 1000,
        numbers: [ 4 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: [ 'sqrt', 'square', 'sum' ],
        postfixOperators: [ '!' ],
        maxFactorial: 10,
        maxExponent: 10,
        maxSquare: 100,
        maxSum: 100,
        applyToEvaluation: false,
    },


    factorialATE: {
        name: 'factorialATE',
        maxGoal: 1000,
        numbers: [ 4 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: null,
        postfixOperators: [ '!' ],
        maxFactorial: 10,
        maxExponent: 50,
        maxSquare: 0,
        maxSum: 0,
        applyToEvaluation: true,
    },
    functionsATE: {
        name: 'functionsATE',
        maxGoal: 1000,
        numbers: [ 4 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: [ 'sqrt', 'square', 'sum' ],
        postfixOperators: null,
        maxFactorial: 10,
        maxExponent: 10,
        maxSquare: 100,
        maxSum: 100,
        applyToEvaluation: true,
    },
    combinedATE: {
        name: 'combinedATE',
        maxGoal: 1000,
        numbers: [ 4 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: [ 'sqrt', 'square', 'sum' ],
        postfixOperators: [ '!' ],
        maxFactorial: 10,
        maxExponent: 10,
        maxSquare: 100,
        maxSum: 100,
        applyToEvaluation: true,
    },



    simpleAll: {
        name: 'simpleAll',
        maxGoal: 1000,
        numbers: [ 4, 44, 444, 4444, .4, 4.4, .44, 44.4, 4.44, .444, 444.4, 44.44, 4.444, .4444 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: null,
        postfixOperators: null,
        maxFactorial: 0,
        maxExponent: 0,
        maxSquare: 0,
        maxSum: 0,
        applyToEvaluation: false,
    },
    factorialAll: {
        name: 'factorialAll',
        maxGoal: 1000,
        numbers: [ 4, 44, 444, 4444, .4, 4.4, .44, 44.4, 4.44, .444, 444.4, 44.44, 4.444, .4444 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: null,
        postfixOperators: [ '!' ],
        maxFactorial: 10,
        maxExponent: 50,
        maxSquare: 0,
        maxSum: 0,
        applyToEvaluation: false,
    },
    functionsAll: {
        name: 'functionsAll',
        maxGoal: 1000,
        numbers: [ 4, 44, 444, 4444, .4, 4.4, .44, 44.4, 4.44, .444, 444.4, 44.44, 4.444, .4444 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: [ 'sqrt', 'square', 'sum' ],
        postfixOperators: null,
        maxFactorial: 10,
        maxExponent: 10,
        maxSquare: 100,
        maxSum: 100,
        applyToEvaluation: false,
    },
    combinedAll: {
        name: 'combinedAll',
        maxGoal: 1000,
        numbers: [ 4, 44, 444, 4444, .4, 4.4, .44, 44.4, 4.44, .444, 444.4, 44.44, 4.444, .4444 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: [ 'sqrt', 'square', 'sum' ],
        postfixOperators: [ '!' ],
        maxFactorial: 10,
        maxExponent: 10,
        maxSquare: 100,
        maxSum: 100,
        applyToEvaluation: false,
    },
    factorialAllATE: {
        name: 'factorialAllATE',
        maxGoal: 1000,
        numbers: [ 4, 44, 444, 4444, .4, 4.4, .44, 44.4, 4.44, .444, 444.4, 44.44, 4.444, .4444 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: null,
        postfixOperators: [ '!' ],
        maxFactorial: 10,
        maxExponent: 50,
        maxSquare: 0,
        maxSum: 0,
        applyToEvaluation: true,
    },
    functionsAllATE: {
        name: 'functionsAllATE',
        maxGoal: 1000,
        numbers: [ 4, 44, 444, 4444, .4, 4.4, .44, 44.4, 4.44, .444, 444.4, 44.44, 4.444, .4444 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: [ 'sqrt', 'square', 'sum' ],
        postfixOperators: null,
        maxFactorial: 10,
        maxExponent: 10,
        maxSquare: 100,
        maxSum: 100,
        applyToEvaluation: true,
    },
    combinedAllATE: {
        name: 'combinedAllATE',
        maxGoal: 1000,
        numbers: [ 4, 44, 444, 4444, .4, 4.4, .44, 44.4, 4.44, .444, 444.4, 44.44, 4.444, .4444 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: [ 'sqrt', 'square', 'sum' ],
        postfixOperators: [ '!' ],
        maxFactorial: 10,
        maxExponent: 10,
        maxSquare: 100,
        maxSum: 100,
        applyToEvaluation: true,
    },


    advanced: {
        name: 'advanced',
        maxGoal: 1000,
        numbers: [ 4, 44, 444, 4444, .4, 4.4, .44, 44.4, 4.44, .444, 444.4, 44.44, 4.444, .4444 ],
        infixOperators: [ '*', '/', '+', '-', '^' ],
        prefixOperators: [ 'sqrt', 'square', 'sum' ],
        postfixOperators: [ '!' ],
        maxFactorial: 10,
        maxExponent: 10,
        maxSquare: 100,
        maxSum: 100,
        applyToEvaluation: false,
    },
};
